### ISSUE TITLE
Suppression du lien symbolique inutile

### ISSUE THREAD

**Issue by baby-gnu** [pichar-v/guitte#3]
Bonjour,

Le fichier `guitte.py` peut être renommé `guitte`, supprimant de fait le besoin du lien symbolique.

De plus, utiliser des extensions sur des scripts exécutable est considéré comme une mauvaise pratique :
- Nous ne somme pas sous windows là !
- Cela pose problème pour réimplémenter une commande dans un autre language.

Merci.

**Comment by w3st3ry** [comment]
Bonjour,

En effet c'était prévu dans la LISTEÀFAIRE, voilà qui est fait maintenant.
